[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "WenliangChang", email = "changwenliang666@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "cryptography>=50.0.1",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "langgraph>=1.2.12",
    "pydantic-settings>=2.15.0",
    "pymysql>=1.2.3",
    "redis>=8.1.0",
    "sqlalchemy>=2.0.54",
    "uvicorn>=0.53.0",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
]
